import {
  ErButton,
  ErIcon,
  ErAlert,
  ErButtonGroup,
  ErCollapse,
  ErCollapseItem,
  ErTooltip,
  ErPopconfirm,
  ErDropdown,
  ErDropdownItem,
  ErConfigProvider,
  ErMessage,
  ErNotification,
  ErInput,
  ErMessageBox,
  ErLoading,
} from "@toy-element/components";
import type { Plugin } from "vue";

export default [
  ErButton,
  ErIcon,
  ErAlert,
  ErButtonGroup,
  ErCollapse,
  ErCollapseItem,
  ErTooltip,
  ErPopconfirm,
  ErDropdown,
  ErDropdownItem,
  ErConfigProvider,
  ErMessage,
  ErNotification,
  ErInput,
  ErMessageBox,
  ErLoading,
] as Plugin[];
